networks:
  debezium:


services:
  zookeeper:
    image: debezium/zookeeper:2.7
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    networks:
      - debezium

  kafka:
    image: debezium/kafka:2.7
    container_name: kafka
    ports:
      - "9094:9094"
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_REPLICA_FETCH_MAX_BYTES=20971520
      - KAFKA_MAX_REQUEST_SIZE=20971520
      - KAFKA_MESSAGE_MAX_BYTES=20971520
      - KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=20971520
    networks:
        - debezium

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  connect:
    image: debezium/connect:2.7
    container_name: connect
    ports:
      - "8083:8083"
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_MAX_REQUEST_SIZE=20971520
      - CONNECT_BUFFER_MEMORY=20971520
      - CONNECT_FETCH_MAX_BYTES=20971520
      - CONNECT_MAX_PARTITION_FETCH_BYTES=20971520
      - CONNECT_PRODUCER_MAX_REQUEST_SIZE=20971520
      - CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES=20971520
      - CONNECT_MESSAGE_MAX_BYTES=20971520
    volumes:
      - connect-logs:/kafka/connect/logs
    networks:
        - debezium
volumes:
  kafka-data:
  zookeeper-data:
  connect-logs:
